import { COMPANY_TIMEZONE, COMPANY_TIMEZONE_OFFSET_MINS, COMPANY_TIMEZONE_OFFSET_STR } from '@/hr360-app/config/timezone';

export const COMPANY_TIMEZONE = COMPANY_TIMEZONE;
export const COMPANY_TIMEZONE_OFFSET_MINS = COMPANY_TIMEZONE_OFFSET_MINS;
export const COMPANY_TIMEZONE_OFFSET_STR = COMPANY_TIMEZONE_OFFSET_STR;
